Add constraint to all applicable data types in ballerina
ballerina-platform/openapi-tools pull request #1020
Opened 2022-06-27 12:22 UTC by lnash94

## Purpose
>  Fix #975

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2022-07-14 05:53 UTC, ldclakmal commented
Reviewed the constraint package usages in test cases. LGTM.

2022-07-14 08:34 UTC, NipunaRanasinghe requested changes

2022-07-14 08:34 UTC, NipunaRanasinghe commented on openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorUtils.java
> +            for (Map.Entry<String, Schema> e : value.getProperties().entrySet()) {
Cant we simplify the loop as follows?

```suggestion
            for (Schema<?> propertyValue : value.getProperties().values()) {
```

2022-07-14 08:34 UTC, NipunaRanasinghe commented on openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorUtils.java
> +            for (Map.Entry<String, Schema> e : value.getProperties().entrySet()) {
You can further improve the logic using stream APIs (`anyMatch(Predicate<? super T> predicate)`)

2022-07-14 09:01 UTC, lnash94 commented on openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/TypeGeneratorUtils.java
> +        AnnotationNode annotationNode = createAnnotationNode(CONSTRAINT_INT, annotBody);
This function receives an integer scheme or Number  Schema. There is a condition for checking the number schema. will move this to else block.

2022-07-15 04:13 UTC, NipunaRanasinghe approved these changes
LGTM

2022-07-15 04:14 UTC, merged